@BibliotecaMusicalBack.Api_HostAddress = http://localhost:5171

GET {{BibliotecaMusicalBack.Api_HostAddress}}/api/generos
Accept: application/json

###

GET {{BibliotecaMusicalBack.Api_HostAddress}}/api/albums/1
Accept: application/json

###

POST {{BibliotecaMusicalBack.Api_HostAddress}}/api/generos
Content-Type: application/json

{
  "genNombre": "Ambient",
  "genDescripcion": "Música atmosférica.",
  "genActivo": true
}
